### ISSUE TITLE
Question (game.png and game.atlas) Icons

### ISSUE THREAD

**Issue by SchoeniosX** [chenxing61/Emperors-and-Deities#1]
Hello Chenxing61,

I apologize for asking you about that.
You have two files named “game.png” and “game atlas”. As far as I know, all icons in an image are mapped in “game png” and all positions (icons) of this image “game.png” are mapped in “game.atlas”. But my question is, how does the game recognize that the respective image belongs to the respective “Building.Icon”? 

I was told to delete game.png and game.atlas to make the in-game images appear compatible, but why would you do that? You provide the icons or why would you? 

On the other hand, I saw that all the moderators had their symbols depicted in an image. But how can this be done? That you added all icons in one image? 

Like I said; The “game.atlas” only exists as the position of the icons (I think). Forgive my questions, I'm just not sure how to add images to the mod properly. However, I would be happy if you have time to answer my questions. 

Kind regards, Laurin S.

**Comment by chenxing61** [comment]
Dear Laurin S
hey bro the images are stored in image folder, just follow the file structure and launch the game once, game image and altas will be automatically generated, if something goes wrong just delete those and try again.
Also the images are 100×100 pixels in size
Best reguard
Cx61

**Comment by SchoeniosX** [comment]
Hello Chenxing61,

Thank you, that explained my question.

Sincerely Laurin S.

chenxing61 ***@***.***> schrieb am Mo., 1. Juli 2024, 05:38:
